config/routes.rb
Testimonials::Application.routes.draw do
  devise_for :users, controllers: {registrations: "registrations"}

  resources :feedbacks
  resources :testimonials
  resources :users do 
    resources :web_links
    resources :feedbacks, only: :new
    resources :users_courses, only: :create
  end
  resources :pages
  resources :courses

  root to: "welcome#index"
  get "/:slug", to: "pages#show"

end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  belongs_to :user
  validates :body, presence: true
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :admin_only, except: [:create, :new]
  before_action :set_feedback, only: [:show, :edit, :update, :destroy]

  # GET /feedbacks
  # GET /feedbacks.json
  def index
    @feedbacks = Feedback.all
  end

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show
  end

  # GET /feedbacks/new
  def new
    @feedback = Feedback.new
  end

  # GET /feedbacks/1/edit
  def edit
  end

  # POST /feedbacks
  # POST /feedbacks.json
  def create
    @feedback = current_user.feedbacks.build(feedback_params)

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to :back, notice: 'Feedback was successfully created.' }
        format.json
      else
        format.html { render action: 'new' }
        format.json
      end
    end
  end

  # PATCH/PUT /feedbacks/1
  # PATCH/PUT /feedbacks/1.json
  def update
    respond_to do |format|
      if @feedback.update(feedback_params)
        format.html { redirect_to :back, notice: 'Feedback was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.json
  def destroy
    @feedback.destroy
    respond_to do |format|
      format.html { redirect_to feedbacks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feedback
      @feedback = Feedback.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feedback_params
      params.require(:feedback).permit(:user_id, :subject, :body)
    end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/_form.html.erb
<% @feedback ? feedback = @feedback : nil %>

<%= form_for(feedback) do |f| %>
  <% if feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

      <ul>
      <% feedback.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, class: "form-control", rows: "7" %>
  </div>

  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-default" %>
  </div>
<% end %>

app/views/feedbacks/create.js.erb
alert('sweeet')

app/views/feedbacks/edit.html.erb
<h1>Editing feedback</h1>

<%= render 'form' %>

<%= link_to 'Show', @feedback %> |
<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/index.html.erb
<h1>Listing feedbacks</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Subject</th>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @feedbacks.each do |feedback| %>
      <tr>
        <td><%= feedback.user.name %></td>
        <td><%= feedback.subject %></td>
        <td><%= feedback.body %></td>
        <td><%= link_to 'Show', feedback %></td>
        <td><%= link_to 'Edit', edit_feedback_path(feedback) %></td>
        <td><%= link_to 'Destroy', feedback, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feedback', new_feedback_path %>

app/views/feedbacks/new.html.erb
<h1>New feedback</h1>

<%= render 'form' %>

<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @feedback.user_id %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @feedback.subject %>
</p>

<p>
  <strong>Body:</strong>
  <%= @feedback.body %>
</p>

<%= link_to 'Edit', edit_feedback_path(@feedback) %> |
<%= link_to 'Back', feedbacks_path %>