config/routes.rb
Testimonials::Application.routes.draw do
  devise_for :users, controllers: {registrations: "registrations"}

  resources :feedbacks
  resources :testimonials
  resources :users do 
    resources :web_links
    resources :feedbacks, only: :new
    resources :users_courses, only: :create
  end
  resources :pages
  resources :courses

  root to: "welcome#index"
  get "/:slug", to: "pages#show"

end

app/models/testimonial.rb
# == Schema Information
#
# Table name: testimonials
#
#  id           :integer          not null, primary key
#  body         :text
#  created_at   :datetime
#  updated_at   :datetime
#  recipient_id :integer
#  user_id      :integer
#

class Testimonial < ActiveRecord::Base
  belongs_to :user
  belongs_to :recipient, class_name: "User"
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  before_action :admin_only, except: [:new, :create]
  before_filter :authenticate_user!
  before_action :set_testimonial, only: [:show, :edit, :update, :destroy]

  # GET /testimonials
  # GET /testimonials.json
  def index
    @testimonials = Testimonial.all
  end

  # GET /testimonials/1
  # GET /testimonials/1.json
  def show
  end

  # GET /testimonials/new
  def new
    @testimonial = Testimonial.new
  end

  # GET /testimonials/1/edit
  def edit
  end

  # POST /testimonials
  # POST /testimonials.json
  def create
    @testimonial = current_user.testimonials.build(testimonial_params)

    respond_to do |format|
      if @testimonial.save
        UserMailer.notification(@testimonial.recipient).deliver
        format.html { redirect_to :back, notice: "Testimonial was successfully created for #{@testimonial.recipient.name}" }
        format.json { render action: 'show', status: :created, location: @testimonial }
      else
        format.html { render action: 'new' }
        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /testimonials/1
  # PATCH/PUT /testimonials/1.json
  def update
    respond_to do |format|
      if @testimonial.update(testimonial_params)
        format.html { redirect_to @testimonial, notice: 'Testimonial was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testimonials/1
  # DELETE /testimonials/1.json
  def destroy
    @testimonial.destroy
    respond_to do |format|
      format.html { redirect_to testimonials_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_testimonial
      @testimonial = Testimonial.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def testimonial_params
      params.require(:testimonial).permit(:body, :recipient_id)
    end
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/views/testimonials/_form.html.erb
<%= form_for(@testimonial) do |f| %>
  <% if @testimonial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@testimonial.errors.count, "error") %> prohibited this testimonial from being saved:</h2>

      <ul>
      <% @testimonial.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :body, class: "form-control", "placeholder" => "Write your testimonial here...", rows: 3 %>
  </div>
  <div class="actions">
    <%= f.hidden_field :recipient_id, value: user_id %>
    <%= f.submit "Submit", class: "btn btn-default" %>
  </div>
<% end %>

app/views/testimonials/_testimonial.html.erb
<div class="col-lg-6 col-md-6 col-sm-6 testimonial">
  <p class="speechbubble"><%= testimonial.body %></p>
  <span class="speechbubble-tri"></span>
  
  <a href="<%= user_path testimonial.user %>" class="pull-right">- <%= testimonial.user.name %></a>
</div>

app/views/testimonials/edit.html.erb
<h1>Editing testimonial</h1>

<%= render 'form' %>

<%= link_to 'Show', @testimonial %> |
<%= link_to 'Back', testimonials_path %>

app/views/testimonials/index.html.erb
<h1>Listing testimonials</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @testimonials.each do |testimonial| %>
      <tr>
        <td><%= testimonial.body %></td>
        <td><%= link_to 'Show', testimonial %></td>
        <td><%= link_to 'Edit', edit_testimonial_path(testimonial) %></td>
        <td><%= link_to 'Destroy', testimonial, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Testimonial', new_testimonial_path %>

app/views/testimonials/new.html.erb
<h1>New testimonial</h1>

<%= render 'form' %>

<%= link_to 'Back', testimonials_path %>

app/views/testimonials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @testimonial.body %>
</p>
<p>
  <strong>From:</strong>
  <%= @testimonial.user.name %>
</p>
<p>
  <strong>To:</strong>
  <%= @testimonial.recipient.name %>
</p>

<%= link_to 'Edit', edit_testimonial_path(@testimonial) %> |
<%= link_to 'Back', testimonials_path %>