config/routes.rb
Testimonials::Application.routes.draw do
  devise_for :users, controllers: {registrations: "registrations"}

  resources :feedbacks
  resources :testimonials
  resources :users do 
    resources :web_links
    resources :feedbacks, only: :new
    resources :users_courses, only: :create
  end
  resources :pages
  resources :courses

  root to: "welcome#index"
  get "/:slug", to: "pages#show"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TCM Testimonials</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href='http://fonts.googleapis.com/css?family=Shadows+Into+Light+Two|Open+Sans' rel='stylesheet' type='text/css'>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">TCM Testimonials</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/">Home</a></li>
        <% Page.all.each do |page| %>
          <li><a href="/<%= page.title %>"><%= page.title.titleize %></a></li>
        <% end %>
        <li>
          <%= link_to 'Feedback', new_user_feedback_path(current_user), :'data-toggle' => 'modal', :'data-target' => '#feedback' if user_signed_in? %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <form class="navbar-form navbar-left" role="search" action="<%= users_path %>" method="get">
          <div class="form-group">
            <input name="q" type="text" class="form-control" placeholder="Search User">
          </div>
          <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
        </form>
        <% if user_signed_in? %>
          <li class="dropdown">
          <%= link_to "Hello, #{current_user.name} <b class='caret'></b>".html_safe, user_path(current_user), class: "dropdown-toggle", "data-toggle"=>"dropdown"  %>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", user_path(current_user) %></li>
            <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
            <% if current_user.admin? %>
              <li class="divider"></li>
              <% { "Courses" => courses_path, "Feedback" => feedbacks_path, "Pages" => pages_path, "Testimonials" => testimonials_path, "Users" => users_path }.each_pair do |name, path| %>
                <li><%= link_to name, path %></li>
              <% end %>


            <% end %>
            <li class="divider"></li>
            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
        <% else %>
          <li><a href="<%= new_user_session_path %>">Log In</a></li>
          <li><%= link_to "Register", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<% if flash.present? %>
  <% flash.keys.each do |key| %>
    <div class="alert alert-<%= flash_css_class(key) %>">
      <%= flash[key] %>
    </div>
  <% end %>
<% end %>

  <%= yield %>

  <div id="feedback" class="modal fade">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Leave Feedback</h4>
        </div>
        <div class="modal-body">
          <%= render partial: 'feedbacks/form', locals: { feedback: Feedback.new } %>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->

</body>
</html>